#!/bin/bash
# Generate E2E Dockerfile Skill
# Generates or locates a Dockerfile for running e2e tests in a container

set -e

# Ensure E2E_PATH is set (should be from discover-e2e-tests)
if [ -z "$E2E_PATH" ]; then
    echo "Warning: E2E_PATH not set, attempting to discover..."
    # Try to discover
    for dir in test/e2e tests/e2e e2e pkg/e2e test/e2e-test; do
        if [ -d "$dir" ] && find "$dir" -name "*_test.go" -type f 2>/dev/null | head -1 | grep -q .; then
            E2E_PATH="$dir"
            break
        fi
    done

    if [ -z "$E2E_PATH" ]; then
        echo "Error: E2E_PATH not set and could not be discovered" >&2
        echo "Please run discover-e2e-tests skill first" >&2
        exit 1
    fi
fi

# Check for existing Dockerfiles
DOCKERFILE_CANDIDATES=(
    "Dockerfile.ci"
    "Dockerfile.e2e"
    "Dockerfile.test"
    "build/Dockerfile.ci"
    "build/Dockerfile"
    "hack/Dockerfile"
)

DOCKERFILE=""
for dockerfile in "${DOCKERFILE_CANDIDATES[@]}"; do
    if [ -f "$dockerfile" ]; then
        echo "Found existing Dockerfile: $dockerfile"

        # Check if it's suitable for Go testing
        if grep -q "go build\|go test\|go mod" "$dockerfile" 2>/dev/null; then
            echo "Dockerfile appears suitable for Go testing"
            DOCKERFILE="$dockerfile"
            break
        else
            echo "Warning: Dockerfile may not be suitable for Go e2e tests"
        fi
    fi
done

# Generate Dockerfile if none found
if [ -z "$DOCKERFILE" ]; then
    echo "No suitable Dockerfile found, generating Dockerfile.ci..."

    # Get Go version from go.mod (default to 1.22)
    GO_VERSION="1.22"
    if [ -f "go.mod" ]; then
        # Try to extract Go version from go.mod
        if grep -q "^go " go.mod; then
            GO_VERSION=$(grep "^go " go.mod | awk '{print $2}')
        fi
    fi

    cat > Dockerfile.ci << EOF
# E2E Test Dockerfile
# Generated by openshift:run-e2e-tests-in-container

# Use OpenShift Go builder image
FROM registry.ci.openshift.org/openshift/release:golang-${GO_VERSION} AS builder

# Set working directory
WORKDIR /go/src/app

# Copy the entire source code
COPY . .

# Download dependencies
RUN go mod download

# Set the default command to run e2e tests
# The kubeconfig should be mounted at /kubeconfig/config
ENV KUBECONFIG=/kubeconfig/config

# Run e2e tests
CMD ["go", "test", "-timeout", "0", "./${E2E_PATH}/...", "-v", "-kubeconfig=/kubeconfig/config"]
EOF

    DOCKERFILE="Dockerfile.ci"
    echo "Generated: $DOCKERFILE"
fi

# Export variables
export DOCKERFILE

# Output results
echo ""
echo "DOCKERFILE=$DOCKERFILE"
echo "E2E_PATH=$E2E_PATH"
