#!/usr/bin/env python3
"""Generate the MkDocs marketplace site from repository metadata.

The marketplace and plugin source files remain the source of truth. Generated
Markdown and MkDocs configuration are intentionally ignored by Git and rebuilt
locally or by the GitHub Pages workflow.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml


REPO_ROOT = Path(__file__).resolve().parent.parent
SITE_NAME = "AI Helpers Marketplace"
SITE_URL = "https://openshift-eng.github.io/ai-helpers/"
REPO_URL = "https://github.com/openshift-eng/ai-helpers"
GENERATED_MARKER = "<!-- Generated by scripts/generate_site.py. Do not edit. -->"

MKDOCS_CONFIG = f"""\
site_name: {SITE_NAME}
site_url: {SITE_URL}
repo_url: {REPO_URL}
repo_name: openshift-eng/ai-helpers

theme:
  name: material
  font: false
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.copy
    - toc.follow

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - toc:
      permalink: true

plugins:
  - search

extra_css:
  - assets/stylesheets/extra.css

"""


@dataclass(frozen=True)
class Item:
    """A command, skill, or agent exposed by a local plugin."""

    kind: str
    name: str
    description: str
    source_path: str
    argument_hint: str = ""

    @property
    def slug(self) -> str:
        return slugify(self.name)


@dataclass
class Plugin:
    """Documentation metadata for one marketplace plugin."""

    name: str
    description: str
    version: str
    category: str
    keywords: list[str]
    author: str
    source_url: str
    local_path: Path | None
    commands: list[Item] = field(default_factory=list)
    skills: list[Item] = field(default_factory=list)
    agents: list[Item] = field(default_factory=list)

    @property
    def item_count(self) -> int:
        return len(self.commands) + len(self.skills) + len(self.agents)


def slugify(value: str) -> str:
    """Return a stable URL-safe name for generated paths."""
    slug = re.sub(r"[^a-z0-9._-]+", "-", value.strip().lower()).strip("-")
    slug = slug or "item"
    if slug in {".", ".."}:
        raise ValueError(f"Cannot generate a path for {value!r}: {slug!r} is reserved")
    return slug


def one_line(value: Any) -> str:
    """Normalize prose for cards and Markdown tables."""
    return " ".join(str(value or "").split())


def table_text(value: Any) -> str:
    """Escape prose for use inside a Markdown table cell."""
    return one_line(value).replace("|", "\\|")


def category_name(category: str) -> str:
    if not category:
        return "Uncategorized"
    display_names = {
        "ci": "CI",
        "olm": "OLM",
    }
    if category in display_names:
        return display_names[category]
    return category.replace("-", " ").title()


def load_frontmatter(path: Path) -> tuple[dict[str, Any], str]:
    """Read YAML frontmatter and body from a Markdown file."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return {}, text

    closing = text.find("\n---\n", 4)
    if closing == -1:
        return {}, text

    metadata = yaml.safe_load(text[4:closing]) or {}
    if not isinstance(metadata, dict):
        metadata = {}
    return metadata, text[closing + 5 :]


def body_summary(body: str) -> str:
    """Use the first prose paragraph when frontmatter has no description."""
    paragraphs: list[str] = []
    for block in re.split(r"\n\s*\n", body):
        candidate = one_line(block)
        if not candidate or candidate.startswith(("#", "```", "<")):
            continue
        paragraphs.append(candidate)
    return paragraphs[0] if paragraphs else ""


def discover_items(repo_root: Path, plugin_dir: Path, kind: str) -> list[Item]:
    """Discover one kind of plugin content and read its frontmatter."""
    patterns = {
        "command": "commands/**/*.md",
        "skill": "skills/**/SKILL.md",
        "agent": "agents/**/*.md",
    }
    items: list[Item] = []
    for path in sorted(plugin_dir.glob(patterns[kind])):
        metadata, body = load_frontmatter(path)
        default_name = path.parent.name if kind == "skill" else path.stem
        name = one_line(metadata.get("name")) or default_name
        description = one_line(metadata.get("description")) or body_summary(body)
        source_path = path.relative_to(repo_root).as_posix()
        items.append(
            Item(
                kind=kind,
                name=name,
                description=description
                or f"{category_name(kind)} provided by this plugin.",
                source_path=source_path,
                argument_hint=one_line(metadata.get("argument-hint")),
            )
        )
    return sorted(items, key=lambda item: item.name.lower())


def local_plugin_path(repo_root: Path, source: Any) -> Path | None:
    """Resolve a local marketplace source without allowing path traversal."""
    if not isinstance(source, str) or not source.startswith("./"):
        return None
    candidate = (repo_root / source[2:]).resolve()
    try:
        candidate.relative_to(repo_root.resolve())
    except ValueError:
        return None
    return candidate if candidate.is_dir() else None


def source_url(source: Any) -> str:
    """Return the GitHub browsing URL for a marketplace source."""
    if isinstance(source, str):
        if source.startswith("./"):
            return f"{REPO_URL}/tree/main/{source[2:]}"
        return source

    if not isinstance(source, dict):
        return REPO_URL
    repo = source.get("repo")
    if not repo:
        return source.get("url", REPO_URL)
    ref = source.get("ref", "main")
    path = str(source.get("path", "")).strip("/")
    url = f"https://github.com/{repo}/tree/{ref}"
    return f"{url}/{path}" if path else url


def load_plugins(repo_root: Path, marketplace_path: Path) -> tuple[dict, list[Plugin]]:
    """Load marketplace entries and enrich local ones from their source trees."""
    marketplace = json.loads(marketplace_path.read_text(encoding="utf-8"))
    plugins: list[Plugin] = []
    for entry in marketplace.get("plugins", []):
        local_path = local_plugin_path(repo_root, entry.get("source"))
        plugin_metadata: dict[str, Any] = {}
        if local_path:
            metadata_path = local_path / ".claude-plugin" / "plugin.json"
            if metadata_path.exists():
                plugin_metadata = json.loads(metadata_path.read_text(encoding="utf-8"))

        author = entry.get("author", plugin_metadata.get("author", {}))
        if isinstance(author, dict):
            author = author.get("name", "")

        plugin = Plugin(
            name=entry["name"],
            description=one_line(
                entry.get("description", plugin_metadata.get("description"))
            ),
            version=one_line(entry.get("version", plugin_metadata.get("version"))),
            category=one_line(entry.get("category")),
            keywords=[
                one_line(value)
                for value in entry.get("keywords", [])
                if one_line(value)
            ],
            author=one_line(author),
            source_url=source_url(entry.get("source")),
            local_path=local_path,
        )
        if local_path:
            plugin.commands = discover_items(repo_root, local_path, "command")
            plugin.skills = discover_items(repo_root, local_path, "skill")
            plugin.agents = discover_items(repo_root, local_path, "agent")
        plugins.append(plugin)
    return marketplace, plugins


def frontmatter(title: str, *, hide: bool = False) -> list[str]:
    lines = ["---", f"title: {json.dumps(title)}"]
    if hide:
        lines.extend(["hide:", "  - navigation", "  - toc"])
    lines.extend(["---", "", GENERATED_MARKER, ""])
    return lines


def generate_home(marketplace: dict, plugins: list[Plugin]) -> str:
    lines = frontmatter(SITE_NAME, hide=True)
    command_count = sum(len(plugin.commands) for plugin in plugins)
    skill_count = sum(len(plugin.skills) for plugin in plugins)
    agent_count = sum(len(plugin.agents) for plugin in plugins)
    lines.extend(
        [
            "# AI Helpers Marketplace",
            "",
            one_line(marketplace.get("metadata", {}).get("description"))
            or "Claude Code plugins for OpenShift engineering workflows.",
            "",
            f"**{len(plugins)} plugins** · **{command_count} commands** · "
            f"**{skill_count} skills** · **{agent_count} agents**",
            "",
            "[Get started](getting-started.md){ .md-button .md-button--primary }",
            "[Browse every plugin](plugins/index.md){ .md-button }",
            "",
        ]
    )

    grouped: dict[str, list[Plugin]] = {}
    for plugin in plugins:
        grouped.setdefault(plugin.category, []).append(plugin)
    for category in sorted(grouped, key=lambda value: category_name(value).lower()):
        lines.extend(
            [
                f"## {category_name(category)}",
                "",
                '<div class="grid cards" markdown>',
                "",
            ]
        )
        for plugin in sorted(grouped[category], key=lambda value: value.name.lower()):
            version = f" · v{plugin.version}" if plugin.version else ""
            lines.extend(
                [
                    f"-   **[{plugin.name}](plugins/{slugify(plugin.name)}/index.md)**",
                    "",
                    "    ---",
                    "",
                    f"    {plugin.description}",
                    "",
                    f"    **{plugin.item_count} items**{version}",
                    "",
                ]
            )
        lines.extend(["</div>", ""])
    return "\n".join(lines)


def generate_plugins_index(plugins: list[Plugin]) -> str:
    lines = frontmatter("Plugins")
    lines.extend(
        [
            "# Plugins",
            "",
            f"{len(plugins)} plugins are registered in the marketplace.",
            "",
            "| Plugin | Category | Commands | Skills | Agents | Version |",
            "| --- | --- | ---: | ---: | ---: | --- |",
        ]
    )
    for plugin in sorted(plugins, key=lambda value: value.name.lower()):
        version = f"v{plugin.version}" if plugin.version else "—"
        lines.append(
            f"| [{plugin.name}]({slugify(plugin.name)}/index.md) | "
            f"{category_name(plugin.category)} | {len(plugin.commands)} | "
            f"{len(plugin.skills)} | {len(plugin.agents)} | {version} |"
        )
    lines.append("")
    return "\n".join(lines)


def item_relative_path(item: Item) -> str:
    return f"{item.kind}s/{item.slug}.md"


def validate_generated_paths(plugins: list[Plugin]) -> None:
    """Reject derived output paths that would overwrite another page."""
    paths: dict[str, str] = {}

    def register(path: Path, source: str) -> None:
        relative_path = path.as_posix()
        previous = paths.get(relative_path)
        if previous is not None:
            raise ValueError(
                f"Generated path collision at {relative_path!r}: "
                f"{previous} and {source}"
            )
        paths[relative_path] = source

    for plugin in plugins:
        plugin_dir = Path("plugins") / slugify(plugin.name)
        register(plugin_dir / "index.md", f"plugin {plugin.name!r}")
        for item in plugin.commands + plugin.skills + plugin.agents:
            register(
                plugin_dir / item_relative_path(item),
                f"{item.kind} {item.name!r} in plugin {plugin.name!r}",
            )

    categories = {plugin.category for plugin in plugins}
    for category in categories:
        slug = slugify(category or "uncategorized")
        register(
            Path("categories") / f"{slug}.md",
            f"category {category_name(category)!r}",
        )


def generate_plugin_page(plugin: Plugin) -> str:
    lines = frontmatter(plugin.name)
    lines.extend([f"# {plugin.name}", "", plugin.description, ""])
    lines.extend(['!!! info "Plugin details"', ""])
    if plugin.version:
        lines.append(f"    - **Version**: {plugin.version}")
    lines.append(
        f"    - **Category**: [{category_name(plugin.category)}](../../categories/{slugify(plugin.category or 'uncategorized')}.md)"
    )
    if plugin.author:
        lines.append(f"    - **Author**: {plugin.author}")
    lines.append(f"    - **Source**: [Browse repository]({plugin.source_url})")
    if plugin.keywords:
        tags = " ".join(
            f'<span class="tag-pill">{keyword}</span>' for keyword in plugin.keywords
        )
        lines.append(f"    - **Keywords**: {tags}")
    lines.extend(
        [
            "",
            "## Install",
            "",
            "```text",
            f"/plugin install {plugin.name}@ai-helpers",
            "```",
            "",
        ]
    )

    sections = (
        ("Commands", plugin.commands),
        ("Skills", plugin.skills),
        ("Agents", plugin.agents),
    )
    rendered = False
    for title, items in sections:
        if not items:
            continue
        rendered = True
        lines.extend(
            [f"## {title}", "", f"| {title[:-1]} | Description |", "| --- | --- |"]
        )
        for item in items:
            lines.append(
                f"| [{item.name}]({item_relative_path(item)}) | {table_text(item.description)} |"
            )
        lines.append("")
    if not rendered:
        lines.extend(
            [
                '!!! note "External plugin"',
                "",
                "    This plugin is maintained outside this repository. Browse its source for command and skill documentation.",
                "",
            ]
        )
    return "\n".join(lines)


def generate_item_page(plugin: Plugin, item: Item) -> str:
    lines = frontmatter(item.name)
    lines.extend(
        [
            f"# {item.name}",
            "",
            item.description,
            "",
            f"**Plugin**: [{plugin.name}](../index.md)",
            "",
        ]
    )
    if item.kind in {"command", "skill"}:
        hint = f" {item.argument_hint}" if item.argument_hint else ""
        lines.extend(
            [
                "## Usage",
                "",
                "```text",
                f"/{plugin.name}:{item.name}{hint}",
                "```",
                "",
            ]
        )
    source = f"{REPO_URL}/blob/main/{item.source_path}"
    lines.extend(
        ["## Source", "", f"[View `{item.source_path}` on GitHub]({source})", ""]
    )
    return "\n".join(lines)


def generate_category_page(category: str, plugins: list[Plugin]) -> str:
    title = category_name(category)
    lines = frontmatter(title)
    lines.extend(
        [f"# {title}", "", f"{len(plugins)} marketplace plugins in this category.", ""]
    )
    for plugin in sorted(plugins, key=lambda value: value.name.lower()):
        lines.extend(
            [
                f"## [{plugin.name}](../plugins/{slugify(plugin.name)}/index.md)",
                "",
                plugin.description,
                "",
                f"**{plugin.item_count} items**"
                + (f" · **v{plugin.version}**" if plugin.version else ""),
                "",
            ]
        )
    return "\n".join(lines)


def nav_label(value: str) -> str:
    """Quote a navigation label so plugin-provided names remain valid YAML."""
    return json.dumps(value)


def generate_nav(plugins: list[Plugin]) -> str:
    lines = [
        "nav:",
        "  - Home: index.md",
        "  - Getting Started: getting-started.md",
        "  - Plugins:",
        "    - Overview: plugins/index.md",
    ]
    for plugin in sorted(plugins, key=lambda value: value.name.lower()):
        plugin_slug = slugify(plugin.name)
        items = plugin.commands + plugin.skills + plugin.agents
        if not items:
            lines.append(
                f"    - {nav_label(plugin.name)}: plugins/{plugin_slug}/index.md"
            )
            continue
        lines.extend(
            [
                f"    - {nav_label(plugin.name)}:",
                f"      - Overview: plugins/{plugin_slug}/index.md",
            ]
        )
        for title, group in (
            ("Commands", plugin.commands),
            ("Skills", plugin.skills),
            ("Agents", plugin.agents),
        ):
            if not group:
                continue
            lines.append(f"      - {title}:")
            for item in group:
                lines.append(
                    f"        - {nav_label(item.name)}: plugins/{plugin_slug}/{item_relative_path(item)}"
                )

    grouped: dict[str, list[Plugin]] = {}
    for plugin in plugins:
        grouped.setdefault(plugin.category, []).append(plugin)
    lines.append("  - Categories:")
    for category in sorted(grouped, key=lambda value: category_name(value).lower()):
        lines.append(
            f"    - {nav_label(category_name(category))}: categories/{slugify(category or 'uncategorized')}.md"
        )
    return "\n".join(lines) + "\n"


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.rstrip() + "\n", encoding="utf-8")


def generate_site(
    repo_root: Path, marketplace_path: Path, output_dir: Path
) -> list[Plugin]:
    """Regenerate all derived MkDocs content and return discovered plugins."""
    marketplace, plugins = load_plugins(repo_root, marketplace_path)
    validate_generated_paths(plugins)
    docs_dir = output_dir / "docs"
    for generated_dir in (docs_dir / "plugins", docs_dir / "categories"):
        if generated_dir.exists():
            shutil.rmtree(generated_dir)

    write_text(docs_dir / "index.md", generate_home(marketplace, plugins))
    write_text(docs_dir / "plugins" / "index.md", generate_plugins_index(plugins))
    for plugin in plugins:
        plugin_dir = docs_dir / "plugins" / slugify(plugin.name)
        write_text(plugin_dir / "index.md", generate_plugin_page(plugin))
        for item in plugin.commands + plugin.skills + plugin.agents:
            write_text(
                plugin_dir / item_relative_path(item), generate_item_page(plugin, item)
            )

    grouped: dict[str, list[Plugin]] = {}
    for plugin in plugins:
        grouped.setdefault(plugin.category, []).append(plugin)
    for category, category_plugins in grouped.items():
        path = docs_dir / "categories" / f"{slugify(category or 'uncategorized')}.md"
        write_text(path, generate_category_page(category, category_plugins))

    write_text(output_dir / "mkdocs.yml", MKDOCS_CONFIG + generate_nav(plugins))
    return plugins


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--marketplace",
        type=Path,
        default=REPO_ROOT / ".claude-plugin" / "marketplace.json",
    )
    parser.add_argument("--output-dir", type=Path, default=REPO_ROOT / "site")
    args = parser.parse_args()
    plugins = generate_site(REPO_ROOT, args.marketplace, args.output_dir)
    item_count = sum(plugin.item_count for plugin in plugins)
    print(f"Generated MkDocs content for {len(plugins)} plugins and {item_count} items")


if __name__ == "__main__":
    main()
