#!/usr/bin/env python3
"""Classify modules into analysis tiers based on size and complexity.

Tiers:
  full       — total_lines <= 3000, complexity != "low"
               Full source sent to module-analyzer agent.
  api-guided — total_lines 3001-8000, OR low-complexity with multiple files
               Pre-extracted API + truncated source (first 2000 lines).
               Agent reads remaining files from disk as needed.
  api-only   — total_lines > 8000, OR auto-generated code (models, protobuf)
               Pre-extracted API only. No agent dispatch — summary generated
               from API surface + registry data.

Usage:
    python3 classify_modules.py --detection detection.json --registry registry.json
"""

import argparse
import json
import os
import re
import sys

FULL_LINE_LIMIT = 3000
API_GUIDED_LINE_LIMIT = 8000

AUTOGEN_PATTERNS = [
    re.compile(r"models?$", re.IGNORECASE),
    re.compile(r"pb2(_grpc)?\.py$"),
    re.compile(r"generated"),
    re.compile(r"_pb2$"),
]


def is_autogenerated(module_name: str, files: list[str]) -> bool:
    for pattern in AUTOGEN_PATTERNS:
        if pattern.search(module_name):
            return True
    autogen_count = sum(
        1 for f in files if "pb2" in f or "generated" in os.path.basename(f).lower()
    )
    return autogen_count > len(files) * 0.5 and len(files) > 5


def classify(detection: dict, registry: list[dict]) -> dict:
    modules_det = detection.get("modules", {})

    registry_lookup = {}
    for entry in registry:
        registry_lookup[entry.get("module", "")] = entry

    full = []
    api_guided = []
    api_only = []
    assignments = {}

    for mod_name, mod_data in modules_det.items():
        total_lines = mod_data.get("total_lines", 0)
        file_count = mod_data.get("file_count", 0)
        files = mod_data.get("files", [])
        reg = registry_lookup.get(mod_name, {})
        complexity = reg.get("complexity", "low")

        entry = {
            "module": mod_name,
            "total_lines": total_lines,
            "file_count": file_count,
            "files": files,
            "complexity": complexity,
        }

        if total_lines > API_GUIDED_LINE_LIMIT or is_autogenerated(mod_name, files):
            entry["tier"] = "api-only"
            entry["reason"] = (
                "auto-generated code"
                if is_autogenerated(mod_name, files)
                else f"total_lines ({total_lines}) > {API_GUIDED_LINE_LIMIT}"
            )
            api_only.append(entry)
        elif total_lines > FULL_LINE_LIMIT:
            entry["tier"] = "api-guided"
            entry["reason"] = f"total_lines ({total_lines}) > {FULL_LINE_LIMIT}"
            api_guided.append(entry)
        elif complexity == "low" and file_count <= 1:
            entry["tier"] = "api-only"
            entry["reason"] = "low complexity, single file"
            api_only.append(entry)
        elif complexity == "low":
            entry["tier"] = "api-guided"
            entry["reason"] = "low complexity, multiple files"
            api_guided.append(entry)
        else:
            entry["tier"] = "full"
            entry["reason"] = f"within limits ({total_lines} lines, {complexity})"
            full.append(entry)

        assignments[mod_name] = entry["tier"]

    return {
        "full": full,
        "api_guided": api_guided,
        "api_only": api_only,
        "assignments": assignments,
        "counts": {
            "full": len(full),
            "api_guided": len(api_guided),
            "api_only": len(api_only),
            "total": len(full) + len(api_guided) + len(api_only),
        },
    }


def main():
    parser = argparse.ArgumentParser(description="Classify modules into analysis tiers")
    parser.add_argument("--detection", required=True, help="Path to detection.json")
    parser.add_argument("--registry", required=True, help="Path to registry.json")
    args = parser.parse_args()

    with open(args.detection) as f:
        detection = json.load(f)
    with open(args.registry) as f:
        registry = json.load(f)

    result = classify(detection, registry)
    json.dump(result, sys.stdout, indent=2)
    print()


if __name__ == "__main__":
    main()
